name: "Select assignee by comment"
description: "Provide a description here"
author: "Your name or organization here"

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: "check-square"
  color: "red"

runs:
  using: node20
  main: dist/index.js
