name: Assign reviewer by comment
on: [issue_comment, pull_request_review]

jobs:
  assign_review_by_comment:
    runs-on: ubuntu-latest
    steps:
      - name: assign_review_by_comment
        shell: python
        run: |
          import yaml
          import os
          from pathlib import Path

          with Path(os.environ['GITHUB_EVENT_PATH']).open() as file:
            dd = yaml.full_load(file)

          print(dd['comment']['issue_url'])
          print(dd)
