name: Assign reviewer by comment
on: [issue_comment, pull_request_review]

jobs:
  assign_review_by_comment:
    runs-on: ubuntu-latest
    steps:
      - name: assign_review_by_comment
        run: echo ${GITHUB_EVENT_NAME}; cat ${GITHUB_EVENT_PATH}
